[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  included_files = [
    "node_modules/sharp/**/*",
    "pages/api/data/**/*",
    "public/images/**/*"
  ]

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NEXT_SHARP_PATH = "/node_modules/sharp"
  POKEMON_DATA_PATH = "pages/api/data/pokemon.json"
  BASE_URL = "https://your-netlify-site.netlify.app"